"""empty message

Revision ID: 48d019c5f7ad
Revises: 8ec5fe1d6e32
Create Date: 2019-11-10 21:40:02.550110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d019c5f7ad'
down_revision = '8ec5fe1d6e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_big_deal_date'), 'big_deal', ['date'], unique=False)
    op.create_index(op.f('ix_big_deal_trade_type'), 'big_deal', ['trade_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_big_deal_trade_type'), table_name='big_deal')
    op.drop_index(op.f('ix_big_deal_date'), table_name='big_deal')
    # ### end Alembic commands ###
