"""empty message

Revision ID: 50c367524674
Revises: 48d019c5f7ad
Create Date: 2019-11-10 21:57:06.908120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '50c367524674'
down_revision = '48d019c5f7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('big_deal', sa.Column('ts_code', sa.String(length=32), nullable=False, comment='股票代码'))
    op.create_index(op.f('ix_big_deal_ts_code'), 'big_deal', ['ts_code'], unique=False)
    op.drop_index('ix_big_deal_code', table_name='big_deal')
    op.drop_column('big_deal', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('big_deal', sa.Column('code', mysql.VARCHAR(length=32), nullable=False, comment='股票代码'))
    op.create_index('ix_big_deal_code', 'big_deal', ['code'], unique=False)
    op.drop_index(op.f('ix_big_deal_ts_code'), table_name='big_deal')
    op.drop_column('big_deal', 'ts_code')
    # ### end Alembic commands ###
