"""empty message

Revision ID: 6843511c10d0
Revises: 917c40f21d79
Create Date: 2019-11-10 17:02:38.627177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6843511c10d0'
down_revision = '917c40f21d79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('big_deal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('code', sa.String(length=32), nullable=False, comment='股票代码'),
    sa.Column('price', sa.Float(), nullable=False, comment='交易价格'),
    sa.Column('volume', sa.Integer(), nullable=False, comment='交易量'),
    sa.Column('trade_type', sa.String(length=32), nullable=False, comment='交易类型'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_big_deal_code'), 'big_deal', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_big_deal_code'), table_name='big_deal')
    op.drop_table('big_deal')
    # ### end Alembic commands ###
