"""empty message

Revision ID: 8ec5fe1d6e32
Revises: 6843511c10d0
Create Date: 2019-11-10 21:39:16.384149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec5fe1d6e32'
down_revision = '6843511c10d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('big_deal', sa.Column('date', sa.Date(), nullable=False, comment='交易日'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('big_deal', 'date')
    # ### end Alembic commands ###
