"""empty message

Revision ID: 917c40f21d79
Revises: ce25ca0a5a1b
Create Date: 2019-11-10 15:38:16.543152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '917c40f21d79'
down_revision = 'ce25ca0a5a1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_basic_ts_code'), 'stock_basic', ['ts_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_basic_ts_code'), table_name='stock_basic')
    # ### end Alembic commands ###
