"""empty message

Revision ID: b6ab967da74c
Revises: 50c367524674
Create Date: 2019-11-11 20:31:19.834063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ab967da74c'
down_revision = '50c367524674'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('week_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('ts_code', sa.String(length=32), nullable=False, comment='股票代码'),
    sa.Column('close', sa.Float(), nullable=False, comment='收盘价'),
    sa.Column('date', sa.Date(), nullable=False, comment='交易日'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_week_data_date'), 'week_data', ['date'], unique=False)
    op.create_index(op.f('ix_week_data_ts_code'), 'week_data', ['ts_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_week_data_ts_code'), table_name='week_data')
    op.drop_index(op.f('ix_week_data_date'), table_name='week_data')
    op.drop_table('week_data')
    # ### end Alembic commands ###
