"""empty message

Revision ID: ce25ca0a5a1b
Revises: 
Create Date: 2019-11-10 14:34:29.509721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce25ca0a5a1b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_basic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('ts_code', sa.String(length=32), nullable=False, comment='股票代码'),
    sa.Column('name', sa.String(length=32), nullable=False, comment='股票名称'),
    sa.Column('area', sa.String(length=32), nullable=False, comment='交易市场'),
    sa.Column('industry', sa.String(length=32), nullable=False, comment='所属行业'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_basic')
    # ### end Alembic commands ###
