# flask server config
SECRET_KEY: 'G42Q&vM+fF9b(jm/(bxt=6Rl'
SESSION_COOKIE_HTTPONLY: True
PERMANENT_SESSION_LIFETIME: 3600
SESSION_REFRESH_EACH_REQUEST: True

# data format
DATE_FORMAT: '%Y-%m-%d'

# database config here
SQLALCHEMY_DATABASE_URI: 'mysql+pymysql://root:19900403@122.51.164.199:3306/stock'
SQLALCHEMY_TRACK_MODIFICATIONS: true
SQLALCHEMY_POOL_SIZE: 10
SQLALCHEMY_POOL_RECYCLE: 3600

# tushare token
TUASHARE_TOKEN: '3192f9d6f6a5f0bb66bf8b825cf5caf289170ab58c5a13ea5bde7200'